import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { assignBed,getAccommodationOverview,releaseBed } from '../../api/accommodation';
import { listResidents } from '../../api/residents';
import { useActor } from '../../auth/ActorContext';
export default function AccommodationPage(){
 const {actor}=useActor(); const qc=useQueryClient(); const [residentId,setResidentId]=useState('');
 const q=useQuery({queryKey:['accommodation-overview'],queryFn:()=>getAccommodationOverview(actor!),enabled:Boolean(actor)});
 const rs=useQuery({queryKey:['residents','accommodation'],queryFn:()=>listResidents(actor),enabled:Boolean(actor)});
 const m=useMutation({mutationFn:async(x:{type:'ASSIGN'|'RELEASE';bedId?:string;residentId?:string})=>{if(!actor)throw new Error('Chưa xác định người thực hiện.');if(x.type==='ASSIGN'){if(!residentId||!x.bedId)throw new Error('Chọn người cao tuổi.');return assignBed(actor,x.bedId,residentId);}return releaseBed(actor,x.residentId!);},onSuccess:async()=>{await qc.invalidateQueries({queryKey:['accommodation-overview']});await qc.invalidateQueries({queryKey:['residents']});}});
 if(!actor)return <main className="page"><h1>Phòng & Giường</h1><p>Cần xác định nhân viên đang thao tác.</p></main>;
 const d=q.data;
 return <main className="page"><div className="page-heading"><div><h1>Phòng & Giường</h1><p>Quản lý vị trí lưu trú và tình trạng giường theo thời gian thực.</p></div></div>{q.isLoading&&<p>Đang tải…</p>}{q.error&&<div className="card">Không thể tải dữ liệu.</div>}{d&&<><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(130px,1fr))',gap:12,marginBottom:20}}>{[['Tổng giường',d.summary.total],['Đang sử dụng',d.summary.occupied],['Còn trống',d.summary.available],['Đã giữ',d.summary.reserved],['Tạm ngưng',d.summary.unavailable],['Công suất',`${d.summary.occupancyPercentage}%`]].map(([k,v])=><article className="card" key={String(k)}><small>{k}</small><h2>{v}</h2></article>)}</section><section className="card"><label>Người cao tuổi <select value={residentId} onChange={e=>setResidentId(e.target.value)}><option value="">Chọn người cao tuổi</option>{(rs.data??[]).map(({resident})=><option key={resident.residentId} value={resident.residentId}>{resident.displayName}</option>)}</select></label>{m.error&&<p role="alert">{m.error instanceof Error?m.error.message:'Không thể hoàn tất thao tác.'}</p>}</section><section style={{display:'grid',gap:12,marginTop:16}}>{d.items.filter(x=>x.bedId).map(x=><article className="card" key={x.bedId!}><strong>{x.buildingName} / {x.floorName} / {x.roomName} / {x.bedName}</strong><p>Trạng thái: <b>{x.bedStatus}</b></p>{x.residentId?<><p>{x.residentName}{x.careLevel?` · ${x.careLevel}`:''}</p><button type="button" disabled={m.isPending} onClick={()=>m.mutate({type:'RELEASE',residentId:x.residentId!})}>Trả giường</button></>:<button type="button" disabled={m.isPending||!residentId||x.bedStatus!=='AVAILABLE'} onClick={()=>m.mutate({type:'ASSIGN',bedId:x.bedId!})}>Xếp giường</button>}</article>)}</section></>}</main>;
}
