BEGIN;
CREATE TABLE accommodation_buildings(building_id text PRIMARY KEY,code text NOT NULL UNIQUE,name text NOT NULL,status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','INACTIVE')),sort_order integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE accommodation_floors(floor_id text PRIMARY KEY,building_id text NOT NULL REFERENCES accommodation_buildings(building_id),code text NOT NULL,name text NOT NULL,floor_number integer,status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','INACTIVE')),sort_order integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(building_id,code));
CREATE TABLE accommodation_rooms(room_id text PRIMARY KEY,floor_id text NOT NULL REFERENCES accommodation_floors(floor_id),code text NOT NULL,name text NOT NULL,room_type text,status text NOT NULL DEFAULT 'AVAILABLE' CHECK(status IN('AVAILABLE','TEMPORARILY_UNAVAILABLE','MAINTENANCE','INACTIVE')),sort_order integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(floor_id,code));
CREATE TABLE accommodation_beds(bed_id text PRIMARY KEY,room_id text NOT NULL REFERENCES accommodation_rooms(room_id),code text NOT NULL,name text NOT NULL,status text NOT NULL DEFAULT 'AVAILABLE' CHECK(status IN('AVAILABLE','RESERVED','OCCUPIED','TEMPORARILY_UNAVAILABLE','MAINTENANCE','INACTIVE')),sort_order integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(room_id,code));
CREATE TABLE bed_assignments(assignment_id text PRIMARY KEY,bed_id text NOT NULL REFERENCES accommodation_beds(bed_id),resident_id text NOT NULL REFERENCES residents(resident_id),assigned_at timestamptz NOT NULL DEFAULT now(),assigned_by text NOT NULL,assigned_by_role text NOT NULL,ended_at timestamptz,ended_by text,ended_by_role text,end_reason text,created_at timestamptz NOT NULL DEFAULT now(),CHECK((ended_at IS NULL AND ended_by IS NULL AND ended_by_role IS NULL) OR (ended_at IS NOT NULL AND ended_by IS NOT NULL AND ended_by_role IS NOT NULL)));
CREATE TABLE accommodation_audit_events(audit_event_id text PRIMARY KEY,event_type text NOT NULL,aggregate_type text NOT NULL,aggregate_id text NOT NULL,resident_id text,actor_id text NOT NULL,actor_role text NOT NULL,previous_state jsonb,new_state jsonb,occurred_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX idx_accommodation_floors_building ON accommodation_floors(building_id,sort_order,floor_number);
CREATE INDEX idx_accommodation_rooms_floor ON accommodation_rooms(floor_id,sort_order);
CREATE INDEX idx_accommodation_rooms_status ON accommodation_rooms(status);
CREATE INDEX idx_accommodation_beds_room ON accommodation_beds(room_id,sort_order);
CREATE INDEX idx_accommodation_beds_status ON accommodation_beds(status);
CREATE INDEX idx_bed_assignments_bed_history ON bed_assignments(bed_id,assigned_at DESC);
CREATE INDEX idx_bed_assignments_resident_history ON bed_assignments(resident_id,assigned_at DESC);
CREATE UNIQUE INDEX uq_bed_assignments_active_bed ON bed_assignments(bed_id) WHERE ended_at IS NULL;
CREATE UNIQUE INDEX uq_bed_assignments_active_resident ON bed_assignments(resident_id) WHERE ended_at IS NULL;
CREATE INDEX idx_accommodation_audit_aggregate ON accommodation_audit_events(aggregate_type,aggregate_id,occurred_at DESC);
COMMIT;
